services:
  generator:
    image: george124816/generator:latest
    ports:
      - target: 4000
        published: 4000
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
