services:
  generator:
    image: george124816/generator:latest
    ports:
      - target: 4000
        published: 4000
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 3
